name: BustinSkin Events
favicon: null
layout_spectrum: 0.49452
typography_spectrum: 0.31493
title: BustinSkin Events
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#fd7d23'
    - '#000000'
    - '#878787'
    - '#cacaca'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.625
  rhythmicContrast: 0
purpose: []
